wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.19.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752762625
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      - 61
      4: 3.9.18
      5: 0.19.11
      8:
      - 5
      13: linux-x86_64
mode_loss:
  desc: null
  value: factor
pred_activation:
  desc: null
  value: silu
pred_dim_block:
  desc: null
  value: 2
pred_dropouts:
  desc: null
  value: 0.08738376783311334
pred_lr:
  desc: null
  value: 3.0429397107482537e-05
pred_normalization:
  desc: null
  value: batch
pred_num_blocks:
  desc: null
  value: 2
pred_optimizer:
  desc: null
  value: adam
pred_wd:
  desc: null
  value: 0.22382756449471317
pred_width_block:
  desc: null
  value: 128
