wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.19.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752589491
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      - 61
      4: 3.9.18
      5: 0.19.11
      8:
      - 5
      13: linux-x86_64
forecast_activation:
  desc: null
  value: gelu
forecast_dim_block:
  desc: null
  value: 5
forecast_dropouts:
  desc: null
  value: 0.15
forecast_lr:
  desc: null
  value: 0.0005
forecast_normalization:
  desc: null
  value: layer
forecast_num_blocks:
  desc: null
  value: 3
forecast_optimizer:
  desc: null
  value: adamw
forecast_wd:
  desc: null
  value: 0.09
forecast_width_block:
  desc: null
  value: 128
